# -*- coding: utf-8 -*-
"""task 1 a(final).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-RZAYCPRVJWVKiF5nZnRzLbrcXuPdN_
"""

#task 1(a)

given_file = open("/content/input1a.txt", "r")

number_count = int(given_file.readline())

final_result = ''

output_file = open("/content/output1a.txt", "w")

for i in range(number_count):

  test_number = int(given_file.readline())

  if test_number % 2== 0:
    result = f"{test_number} is an Even number.\n"
  else:
    result = f"{test_number} is an Odd number.\n"

  final_result += result

output_file.write(final_result[:-1:])
given_file.close()
output_file.close()