# -*- coding: utf-8 -*-
"""Task 1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEm55zE-fS7WxZ-LQEC-N5KbQEv00NDC
"""

#task 1(b)

given_file = open("/content/input1b.txt", "r")

equation_count = int(given_file.readline())

final_result = ""

output_file = open("/content/output1b.txt", "w")

for i in range(equation_count):

  equation = given_file.readline().split(" ")[1::]

  if "+" in equation:
    result = f"The result of {int(equation[0])} + { int(equation[2])} is {int(equation[0]) + int(equation[2])}\n"

  elif '-' in equation:
    result = f"The result of {int(equation[0])} - { int(equation[2])} is {int(equation[0]) - int(equation[2])}\n"

  elif '*' in equation:
    result = f"The result of {int(equation[0])} * { int(equation[2])} is {int(equation[0]) * int(equation[2])}\n"

  elif '/' in equation:
    result = f"The result of {int(equation[0])} / { int(equation[2])} is {int(equation[0]) / int(equation[2])}\n"

  final_result += result

output_file.write(final_result[:-1:])

output_file.close()
given_file.close()