# -*- coding: utf-8 -*-
"""task1A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KapNe8bBFC-3C7RQVw7V_o_wfnlA6eVw
"""

f=open("input1a_3.txt",'r')
f1=open("output1a_3.txt",'w')

dict1 = {}
a,b = [int(i) for i in f.readline().split()]
for i in range(a+1):
  dict1.update({i:[]})

for lines in f:
  l = lines.split()
  dict1[int(l[0])].append(int(l[1]))


def cycle():
  order=[]
  indegree = [0]*(int(a+1))
  for v in dict1.values():
    for i in v:
      indegree[i]+=1

  Q=[]

  for i in range(1,len(indegree)):
    if(indegree[i]==0):
      Q.append(i)

  while Q!=[]:
    u=Q.pop(0)
    order.append(u)

    for v in dict1[u]:
      indegree[v]-=1
      if(indegree[v]==0):
        Q.append(v)
  return order
output=cycle()

visited=[0]*(a+1)
start=[0]*(a+1)
end=[0]*(a+1)
lst=[]

def dfs(visited, graph, node):
  if visited[node]==0:
    visited[node]=1
    for neighbour in graph[node]:
      dfs(visited, graph, neighbour)


    lst.append(node)
if(len(output)!=a):
  f1.write(f"IMPOSSIBLE")
else:
  for i in range(1,a+1,1):
    if(visited[i]!=1):
      dfs(visited, dict1, i)

  lst.reverse()

  for i in lst:
    f1.write(str(i)+" ")

f.close()
f1.close()