# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KapNe8bBFC-3C7RQVw7V_o_wfnlA6eVw
"""

f=open("input3_1.txt",'r')
f1=open("output3_1.txt",'w')

dict1 = { }
a,b = [int(i) for i in f.readline().split()]
for i in range(1,a+1,1):
  dict1.update({i:[]})

for lines in f:
  l = lines.split()
  dict1[int(l[0])].append(int(l[1]))

def strongly_connected(graph):
  def dfs(u, stack):
    visited[u] = True
    for v in graph[u]:
      if not visited[v]:
        dfs(v, stack)
    stack.append(u)

  def dfs_reverse(u, component):
    visited[u] = True
    component.append(u)
    for v in transposed[u]:
      if not visited[v]:
        dfs_reverse(v, component)

  visited = [False]*(a+1)
  stack =[]
  for u in graph:
    if not visited[u]:
      dfs(u, stack)

  transposed = {u: [] for u in graph}
  for u in graph:
    for v in graph[u]:
      transposed[v].append(u)

  visited = [False]*(a+1)
  result =[]
  while stack:
    u = stack.pop()
    if not visited[u]:
      component =[]
      dfs_reverse(u, component)
      result.append(component)


  for i in sorted(result) :
    for j in i:
      f1.write(f"{j} ")
    f1.write(f"\n")

strongly_connected(dict1)

f.close()
f1.close()