# -*- coding: utf-8 -*-
"""task1B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KapNe8bBFC-3C7RQVw7V_o_wfnlA6eVw
"""

f=open("input1b_3.txt",'r')
f1=open("output1b_3.txt",'w')
read1=f.readline().split()

lst=[[0 for i in range(int(read1[0])+1)] for j in range(int(read1[0])+1)]
lst1 = [0]*(int(read1[0])+1)

for lines in f:
  read=lines.split()
  lst[int(read[0])][int(read[1])]=1



order=[]

def topologicalSort():
  indegree = [0]*(int(read1[0])+1)
  for i in range(len(lst)):
    for j in range(len(lst[i])):
      if lst[i][j]==1:
        indegree[j] += 1


  Q=[]

  for i in range(1,len(indegree)):
    if(indegree[i]==0):
      Q.append(i)


  while Q!=[]:
    u=Q.pop(0)
    order.append(u)

    for v in range(len(lst[u])):
      if(lst[u][v]==1):
        indegree[v]-=1

        if(indegree[v]==0):
          Q.append(v)

topologicalSort()


if(len(order)==int(read1[0])):
  for i in order:
    f1.write(str(i)+" ")

else:
  f1.write(f"IMPOSSIBLE")


f.close()
f1.close()