# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMKRPlV5CkdO68kayrx1Lcek74baULPq
"""

# task 5

inpdata =open("input5_1.txt", "r")
outdata = open("output5_1.txt", "w")
given_val= list(map(int,inpdata.readline().split()))

l = given_val[0] # Number of vertices
q = given_val[1] # Number of edges
r = given_val[2]
list1 = []

for i in range(l+1):
    list1.append([0 for i in range(l+1)])


for i in range(q):
    vals = inpdata.readline().strip()
    vals = list(map(int,vals.split()))
    n_N = vals[0]
    m_M= vals[1]
    list1[n_N][m_M] = 1
    list1[m_M][n_N] = 1

def shortest_path(list1,l,start,end):
    main_one = [0]*(l+1)
    distance = [0]*(l+1) #  distance
    checked_val = [start]     #  visited
    en = [start]
    distance[start] = 0

    while len(en)!=0:
        temp=en.pop(0)   # removing
        if temp != end:
            for k in range(1,l+1):
                if list1[temp][k]==1:  # check edge
                    if k not in checked_val:
                        main_one[k] = temp
                        distance[k] =distance[temp]+1
                        checked_val.append(k)
                        en.append(k)
        else:
            break

    plan = []
    plan.append(temp)
    while temp!=start:
        plan.append(main_one[temp])
        temp = main_one[temp]
    plan= plan[::-1]

    print('Time: ',distance[end], file = outdata)
    print(f"Shortest Path: {' '.join(map(str,plan))}", file =outdata)


shortest_path(list1,l,1,r)

inpdata.close()
outdata.close()




'''code explanation:

firstly we oepn input file, create output file.

Then we read input file data by one line and assign the corresponding integers that represent the number of vertices (l), the number of edges (q), and a specific value (r).

Then we initialize an adjacency matrix list1 that we will use as a 2D list of size (l+1) x (l+1) filled with zeros.

Then we read q lines from the input file, each containing two integers n_N and m_M who represent edges between vertices in an undirected graph. Also we update the adjacency matrix accordingly.

Then using shortest_path function we perform breadth-first search to find the shortest path from the starting vertex to the destination vertex.

And we print and write the to the ouput file

And finally close the input and output file.'''