# -*- coding: utf-8 -*-
"""task1A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMKRPlV5CkdO68kayrx1Lcek74baULPq
"""

inpdata = open("input1a_1.txt", "r")
optdata = open("output1a_1.txt", "w")


def adjacency_matrix(n_N, edges):
    matrix = [[0 for i in range(n_N + 1)] for i in range(n_N + 1)]

    for edge in edges:
        ui, vi, wi = edge
        matrix[ui][vi] = wi
    return matrix


n_N, m_M = map(int, inpdata.readline().split())
edges = []

for i in range(m_M):
    ui, vi, wi = map(int, inpdata.readline().split())
    edges.append((ui, vi, wi))

useable_data = adjacency_matrix(n_N, edges)
for line in useable_data:
    print(*line, file=optdata)

inpdata.close()
optdata.close()


'''code explanation:

we prepare input file to be ready to be read and output file ready to be written over.

The function, adjacency_matrix, It initializes a square matrix with dimensions (n_N + 1) x (n_N + 1) filled with zeros and then, for each edge in the input, it assigns the source node (ui), destination node (vi), and weight (wi), and sets the corresponding entry in the matrix to the weight.

then we read the first line of the input file to get the number of nodes (n_N) and edges (m_M) and then then iterates over the next m_M lines to read the edges, each represented in the following manner: source node (ui), destination node (vi), and weight (wi). And then we store the edge information as a tuple in the edges list.

and finally we write our output data in output file as a matrix. '''