# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMKRPlV5CkdO68kayrx1Lcek74baULPq
"""

#task4

inpdata = open("input4_1.txt", "r")
outdata = open("output4_1.txt", "w")

n_N, m_M = map(int,inpdata.readline().split())
graphdesign = {i: [] for i in range(1, n_N + 1)}

for x in range(m_M):
  u, v = map(int,inpdata.readline().split())
  graphdesign[u].append(v)

def graph_has_cycle(graphdesign):
    visited = [False] * (len(graphdesign) + 1)

    def DFS(node, path):
        visited[node] = True
        path.append(node)

        for nghbr in graphdesign[node]:
            if nghbr in path:
                return True
            elif not visited[nghbr]:
                if DFS(nghbr, path):
                    return True
        path.pop()
        return False

    for node in range(1, len(graphdesign) + 1):
        if not visited[node]:
            if DFS(node, []):
                return True

    return False


if graph_has_cycle(graphdesign):
    outdata.write("YES\n")
else:
  outdata.write("NO\n")

inpdata.close()
outdata.close()