# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMKRPlV5CkdO68kayrx1Lcek74baULPq
"""

#task2
inpdata = open("input2_1.txt","r")
outdata = open("output2_1.txt","w")

readline1 = inpdata.readline()
stringnew1 = readline1.strip()
temp = [int(i) for i in stringnew1.split(" ")]


graph_design = {}
for i in range(1,temp[0]+1):
    graph_design[i] = []

for j in range(temp[1]):
    readline2 =inpdata.readline()
    stringnew2 = readline2.strip()
    lis = [int(i) for i in stringnew2.split()]

    n_N = lis[0]
    m_M = lis[1]
    graph_design[n_N].append(m_M)


def BFS(graph_design, list_val, node):
    list_val.append(node)
    emptyqueue.append(node)

    while emptyqueue:
        node_U = emptyqueue.pop(0)
        outdata.write(str(node_U)+" ")

        for k in graph_design[node_U]:
            if k not in list_val:
                list_val.append(k)
                emptyqueue.append(k)

emptyqueue = []
list_val= []
BFS(graph_design,list_val, 1)

inpdata.close()
outdata.close()