# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMKRPlV5CkdO68kayrx1Lcek74baULPq
"""

#task3

inpdata=open("input3_1.txt","r")
outdata=open("output3_1.txt","w")
n_N, m_M = map(int,inpdata.readline().split())
graph = {i: [] for i in range(n_N + 1)}

for x in range(m_M):
    ui, vi = map(int,inpdata.readline().split())
    graph[ui].append(vi)
    graph[vi].append(ui)


def DFS(graph, begin, output_file):
    visited_path = set()
    stack_flow = [begin]

    while stack_flow:
        vertex_root = stack_flow.pop()
        if vertex_root in visited_path:
            continue

        visited_path.add(vertex_root)
        output_file.write(str(vertex_root) + " ")


        for nighbr in graph[vertex_root]:
            if nighbr not in visited_path:
                stack_flow.append(nighbr)


begin= 1
DFS(graph,begin,outdata)

inpdata.close()
outdata.close()