# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMKRPlV5CkdO68kayrx1Lcek74baULPq
"""

# task 6

inpdata = open("input6_1.txt", "r")
outdata = open("output6_1.txt", "w")
given = inpdata.readline()
given = list(map(int, given.split()))

m = given[0]
n = given[1]
list1 = []

for i in range(m):
    path_visited = inpdata.readline()
    path_visited = path_visited.strip()
    path_visited = [*path_visited]
    list1.append(path_visited)


def dfs(ways, cheked, m, n):
    stack = []
    stack.append([m, n])
    cheked.append([m, n])
    dimond_found = 0

    while len(stack) != 0:
        temp = stack.pop(len(stack) - 1)

        r_R = temp[0]
        c_C = temp[1]
        upon = [r_R - 1, c_C]
        below = [r_R + 1, c_C]
        right_side = [r_R, c_C + 1]
        left_side = [r_R, c_C - 1]

        if ways[r_R][c_C] == "D":
            dimond_found += 1

        if below[0] < given[0]:
            if (below not in cheked) and (ways[below[0]][below[1]] != "#"):
                stack.append(below)
                cheked.append(below)

        if upon[0] > (-1):
            if (upon not in cheked) and (ways[upon[0]][upon[1]] != "#"):
                stack.append(upon)
                cheked.append(upon)

        if left_side[1] > (-1):
            if (left_side not in cheked) and (ways[left_side[0]][left_side[1]] != "#"):
                stack.append(left_side)
                cheked.append(left_side)

        if right_side[1] < given[1]:
            if (right_side not in cheked) and (ways[right_side[0]][right_side[1]] != "#"):
                stack.append(right_side)
                cheked.append(right_side)

    return dimond_found


cheked = []
foundmaxdimond = 0

for i in range(m):
    for j in range(n):
        if [i, j] not in cheked and list1[i][j] != "#":
            foundmaxdimond = max(foundmaxdimond, dfs(list1, cheked, i, j))

print(foundmaxdimond, file=outdata)
inpdata.close()
outdata.close()