# -*- coding: utf-8 -*-
"""task1B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMKRPlV5CkdO68kayrx1Lcek74baULPq
"""

inpdata= open("input1b_1.txt", "r")
optdata = open("output1b_1.txt","w")

def adjacency_list(n_N,edges):
  new_adj_list = [[]for i in range(n_N+1)]

  for edge in edges:
    ui,vi,wi = edge
    new_adj_list[ui].append((vi,wi))
  return new_adj_list

n_N,m_M = map(int,inpdata.readline().split())
edges = []

for i in range(m_M):
  ui,vi,wi = map(int,inpdata.readline().split())
  edges.append((ui,vi,wi))

new_lis = adjacency_list(n_N,edges)
for i in range(0,n_N+1):
   print(i,":",*new_lis[i], file =optdata)

inpdata.close()
optdata.close()


'''

code explanation:

In the function, adjacency_list(), we initialize an empty list of lists called new_adj_list, where each list corresponds to a node in the graph. And then we iterate over each edge in the edges list and append a tuple (vi, wi) to the list at index ui in new_adj_list. This tuple represents an edge from node ui to node vi with weight wi, where new_adj_list is an adjacency list representation of the graph.

Then we read the input file iteratively and assign them correspoing variables and then insert those variables in a tuple and that tuple is appended in the list. In the tuple, tuple is an edge from node ui to node vi with weight wi.

We then call the adjacency_list function with the provided number of nodes and edges and then iterate over the resulting adjacency list (new_lis) and prints each node along with its adjacent nodes and weights to the output file.

Then we finally close the input and output files'''