# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11IhgZA6ulqCGbTxu51rzMz6ZxZ0ZLO-N
"""

infile = open('input2_1.txt', 'r')
outfile = open('output2_1.txt', 'w')

temp = infile.readline().strip().split(' ')
N = int(temp[0])
M = int(temp[1])

vertices = []
d = {}

for i in range(M):
    temp2 = infile.readline().strip().split(' ')
    u = int(temp2[0])
    v = int(temp2[1])
    w = int(temp2[2])
    if u not in vertices:
        vertices.append(u)
    if v not in vertices:
        vertices.append(v)
    if u not in d:
        d[u] = {'adj': [], 'weight': []}
        d[u]['adj'].append(v)
        d[u]['weight'].append(w)
    else:
        d[u]['adj'].append(v)
        d[u]['weight'].append(w)
    if v not in d:
        d[v] = {'adj': [], 'weight': []}

temp3 = infile.readline().strip().split(' ')
S = int(temp3[0])
T = int(temp3[1])

DistanceL1 = [float('inf')] * (N+1)
DistanceL2 = [float('inf')] * (N+1)
DistanceL1[S] = 0
DistanceL2[T] = 0


def dijkstra(graph, start, distanceL):
    distanceL[start] = 0
    q = [start]

    while q:
        exMin = q.index(min(q))
        a = q.pop(exMin)
        b = distanceL[a]

        t = 0

        for i in graph[a]['adj']:
            if (graph[a]['weight'][t] + b) < distanceL[i]:
                distanceL[i] = graph[a]['weight'][t] + b
                q.append(i)

            t += 1


dijkstra(d, S, DistanceL1)
dijkstra(d, T, DistanceL2)

minimum = float('inf')
maximum = float('inf')
idx = 0
edge_pair = []

for i in range(len(DistanceL1)):
    a = DistanceL1[i]
    b = DistanceL2[i]
    if max(a, b) < maximum and a + b <= minimum:
        minimum = a + b
        maximum = max(a, b)
        edge_pair = [a, b]
        idx = i

if idx != 0:
    outfile.write(f'Time {maximum}\nNode {idx}')
else:
    outfile.write(f'Impossible')

outfile.close()