# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11IhgZA6ulqCGbTxu51rzMz6ZxZ0ZLO-N
"""

inp = open('input4_1.txt', 'r')
out = open('output4_1.txt', 'w')
vertices, edges = map(int, inp.readline().split())

edge = []
weight = []

for i in range(edges):
    a, b, w = map(int, inp.readline().split())
    edge.append((a, b))
    weight.append(w)

for i in range(edges):
    for j in range(edges - 1):
        if weight[j] > weight[j + 1]:
            weight[j], weight[j + 1] = weight[j + 1], weight[j]
            edge[j], edge[j + 1] = edge[j + 1], edge[j]

parent = [i for i in range(vertices + 1)]
rank = [0 for i in range(vertices + 1)]

def find(x):
    if parent[x] == x:
        return x
    return find(parent[x])

def union(x, y):
    xroot = find(x)
    yroot = find(y)

    if xroot == yroot:
        return

    if rank[xroot] < rank[yroot]:
        parent[xroot] = yroot

    elif rank[xroot] > rank[yroot]:
        parent[yroot] = xroot

    else:
        parent[yroot] = xroot
        rank[xroot] += 1
# Kruskal's algorithm
def kruskal():
    mst = []
    i = 0
    e = 0

    while e < vertices - 1:
        u, v = edge[i]
        i += 1
        x = find(u)
        y = find(v)

        if x != y:
            e += 1
            mst.append((u, v))
            union(x, y)
    return mst
mst = kruskal()
result = 0
for u, v in mst:
    result += weight[edge.index((u, v))]
out.write(str(result))

inp.close()
out.close()

