# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11IhgZA6ulqCGbTxu51rzMz6ZxZ0ZLO-N
"""

import heapq
f = open("input1.txt", "r")
f1 = open("output1.txt", "w")
N, M = map(int, f.readline().split())

graph = [[] for _ in range(N)]

for _ in range(M):
    u, v, w = map(int, f.readline().split())
    graph[u - 1].append((v - 1, w))

source = int(f.readline()) - 1

def dijkstra(graph, source):
    N = len(graph)
    dist = [float('inf')] * N
    dist[source] = 0

    pq = [(0, source)]
    heapq.heapify(pq)

    while pq:
        curr_dist, curr_node = heapq.heappop(pq)

        if curr_dist > dist[curr_node]:
            continue

        for neighbor, weight in graph[curr_node]:
            new_dist = curr_dist + weight

            if new_dist < dist[neighbor]:
                dist[neighbor] = new_dist
                heapq.heappush(pq, (new_dist, neighbor))

    return dist

distances = dijkstra(graph, source)
for distance in distances:
    if distance == float('inf'):
        distance = -1
    f1.write(str(distance) + " ")

f.close()
f1.close()