# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJCSdm0sGLtz3_mUKUobbP5mB2tLyfNU
"""

#task 4

given_file = open('/content/input4.txt','r')
output_file=open('/content/output4.txt','w')

train_count = int( given_file.readline().strip() )

train_info = {}
temp_str = ''

for i in range(train_count):

    temp = str( given_file.readline().strip() )

    temp_list=temp.split(' ')

    for j in temp_list:

        if temp_list[0] not in train_info:
            train_info[temp_list[0]]=[[temp_list[4], temp_list[-1]]]
        else:
            train_info[temp_list[0]].append([temp_list[4], temp_list[-1]])
        break

train_name=[]
for k in train_info:
    train_name.append(k)

def sort(arr):
  for i in range(len(arr)-1):
    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
  return arr

sort(train_name)

for k in train_info:
  for i in range(len(train_info[k])):
    for j in range(len(train_info[k])-i-1):
      if train_info[k][j][1] < train_info[k][j+1][1]:
        train_info[k][j], train_info[k][j+1]=train_info[k][j+1], train_info[k][j]

final_result = ""

for z in train_name:
  for y in range(len(train_info[z])):
    final_result += f'{z} will departure for {train_info[z][y][0]} is {train_info[z][y][1]}\n'

output_file.write(final_result[:-1:])
given_file.close()
output_file.close()