# -*- coding: utf-8 -*-
"""task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14f-dSZvvug7vgDK9IY2vqkuq9REEvi2R
"""

def absolute_max(arr):
    absolute_max = max(arr, key=abs)
    return absolute_max

def get_max(arr):
    n = len(arr)
    if n == 1:
        return float('-inf')
    if n == 2:
        a = arr[0] + arr[1]**2
        return a

    mid = len(arr) // 2
    left_half = arr[:mid]
    right_half = arr[mid:]
    left_max = get_max(left_half)
    right_max = get_max(right_half)
    cross_max = max(left_half) + absolute_max(right_half)**2

    return max(left_max, right_max,cross_max)


infile = open('input4.txt', 'r')
outfile = open('output4.txt', 'w')

N = int(infile.readline().strip())
lst1 = infile.readline().strip().split()

for i in range(N):
    lst1[i] = int(lst1[i])

result = get_max(lst1)
outfile.write(str(result))

outfile.close()
infile.close()