# -*- coding: utf-8 -*-
"""task 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14f-dSZvvug7vgDK9IY2vqkuq9REEvi2R
"""

def partition(arr, l, h):
    pivot = arr[h]
    i = l-1

    for j in range(l, h):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i+1], arr[h] = arr[h], arr[i+1]
    return i+1


def quick_sort(arr, l, h):
    if l < h:
        idx = partition(arr, l, h)
        quick_sort(arr, l, idx-1)
        quick_sort(arr, idx+1, h)
    return arr


infile = open('input5.txt', 'r')
outfile = open('output5.txt', 'w')

N = int(infile.readline().strip())
arr = infile.readline().strip().split()

for i in range(N):
    arr[i] = int(arr[i])

result = quick_sort(arr, 0, N-1)

for i in range(N):
    outfile.write(f'{result[i]} ')
outfile.close()
infile.close()