# -*- coding: utf-8 -*-
"""task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FiWU6INVeWn8FBWqOSHiZdjQfxhQku4S
"""

def maximum_number(arr):
    if len(arr) == 1:
        return arr[0]
    else:
        max_list = maximum_number(arr[1:])
        if arr[0] > max_list:
            return arr[0]
        else:
            return max_list
given_file = open("input2.txt", "r")
new_lines = [x.strip() for x in given_file.readlines()]
number = maximum_number([eval(y) for y in new_lines[1].split()])
f = open("output2.txt", "w")
f.write(str(number))
f.close()
given_file.close()