# -*- coding: utf-8 -*-
"""task 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14f-dSZvvug7vgDK9IY2vqkuq9REEvi2R
"""

infile = open('input6.txt', 'r')
outfile = open('output6.txt', 'w')

N = int(infile.readline()[0].strip())
arr = infile.readline().strip().split()
queries = int(infile.readline()[0].strip())

for i in range(N):
    arr[i] = int(arr[i])

def partition(arr, l, h):
    pivot = arr[h]
    i = l-1

    for j in range(l, h):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i+1], arr[h] = arr[h], arr[i+1]
    return i+1


def find_min(arr, l, h, min_idx):
    if l == h:
        if l == min_idx:
            return arr[l]
        else:
            return None
    else:
        idx = partition(arr, l, h)
        if idx == min_idx:
            return arr[idx]
        elif min_idx > idx:
            return find_min(arr, idx + 1, h, min_idx)
        else:
            return find_min(arr, l, idx - 1, min_idx)

result = ''
for j in range(queries):
    temp = int(infile.readline().strip())
    result = result + f'{find_min(arr, 0, N-1, temp-1)}\n'
outfile.write(result[:-1:])
outfile.close()
infile.close()