# -*- coding: utf-8 -*-
"""task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14f-dSZvvug7vgDK9IY2vqkuq9REEvi2R
"""

def merge(left_array, right_array):
    merged_array = []
    if (left_array == [] and right_array == []) or (left_array != [] and right_array == []) or (left_array == [] and right_array != []):
       return merged_array or (merged_array + left_array) or (merged_array + right_array)
    elif left_array != [] and right_array != []:
       if left_array[0] <= right_array[0]:
          merged_array += [left_array[0]]
          merged_array = merged_array + merge(left_array[1:], right_array)
       elif left_array[0] > right_array[0]:
          merged_array += [right_array[0]]
          merged_array = merged_array + merge(left_array, right_array[1:])
    return merged_array
def mergeSort(array):
    if len(array) <= 1:
        return array
    else:
        left_array = mergeSort(array[0 : (len(array) // 2)])
        right_array = mergeSort(array[(len(array) // 2) : len(array)])
        return merge(left_array, right_array)

given_file = open("input1.txt", "r")
new_lines = [x.strip() for x in given_file.readlines()]
array = [str(i) for i in mergeSort([eval(y) for y in new_lines[1].split()])]
string = " ".join(array)
f = open("output1.txt", "w")
f.write(string)
f.close()
given_file.close()