# -*- coding: utf-8 -*-
"""task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14f-dSZvvug7vgDK9IY2vqkuq9REEvi2R
"""

given_file = open('input3.txt', 'r')
outfile = open('output3.txt', 'w')

N = int(given_file.readline().strip())
heights = given_file.readline().strip().split()

for i in range(len(heights)):
    heights[i] = int(heights[i])

def dnc(arr):
    if len(arr) <= 1:
        return arr, 0

    mid = len(arr) // 2
    a1, c1 = dnc(arr[:mid])
    a2, c2 = dnc(arr[mid:])

    new_list = []
    counter = c1 + c2
    i, j = 0, 0

    while i < len(a1) and j < len(a2):
        if a1[i] <= a2[j]:
            new_list.append(a1[i])
            i += 1
        else:
            new_list.append(a2[j])
            counter += len(a1) - i
            j += 1

    if i < len(a1):
        for l in range(i, len(a1)):
            new_list.append(a1[l])

    if j < len(a2):
        for m in range(j, len(a2)):
            new_list.append(a2[m])

    return new_list, counter


new_arr, count = dnc(heights)
outfile.write(str(count))
outfile.close()
given_file.close()