# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aahKI6Lpn7LdU__wqz9c8UdjtP64u91r
"""

#task 3

given_file = open("/content/input3.txt", "r")

student_count = int(given_file.readline())

def student_info_pair(given_file):
  import numpy as np
  student_ids = given_file.readline().split(" ")
  student_marks = given_file.readline().split(" ")
  student_info = np.array([None]*len(student_ids))
  for i in range(len(student_info)):
    student_info[i] = tuple( (int(student_ids[i]), int(student_marks[i])) )

  return student_info

student_info_array = student_info_pair(given_file)

def student_marks_sort(student_info_array):

  for i in range( len(student_info_array) ):

    max_ind = i

    for j in range( i+1, len(student_info_array) ):

      if student_info_array[j][1] > student_info_array[max_ind][1]:
        max_ind = j

      elif student_info_array[j][1] == student_info_array[max_ind][1]:

        if student_info_array[j][0] < student_info_array[max_ind][0]:
          max_ind = j

    student_info_array[max_ind], student_info_array[i] = student_info_array[i], student_info_array[max_ind]

  return student_info_array

student_info_array = student_marks_sort(student_info_array)

final_result = ""

for i in range( len(student_info_array) ):
  final_result += f"ID: {student_info_array[i][0]} Mark: {student_info_array[i][1]}\n"

output_file = open("/content/output3.txt", "w")

output_file.write(final_result[:-1:])

output_file.close()
given_file.close()