# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xSlil5mNCU3pzzvIF58OSfl_7ZIhyHJ7
"""

#task 2

def bubbleSort(arr):
  swap_flag = False
  for i in range(len(arr)-1):

    for j in range(len(arr)-i-1):

      if arr[j] > arr[j+1]:

        arr[j], arr[j+1] = arr[j+1], arr[j]

        swap_flag = True

    if not swap_flag:
      return arr

import numpy as np

given_file = open("/content/input2.txt", "r")

array_length = int(given_file.readline())

def array_maker(array, array_length):
  array = [int(x) for x in array]
  arr = np.array([0]*array_length)
  for i in range( array_length ):
    arr[i] = array[i]
  return arr

array = given_file.readline().split(" ")
array = array_maker(array, array_length)

sorted_array = bubbleSort(array)

output_file = open("/content/output2.txt", "w")

output_file.write(f"{array}"[1:-1:])

output_file.close()
given_file.close()